apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
   deploy: nginx
spec:
    replicas: 3
    selector:
     matchLabels:
      pod: nginx
    template:
     metadata:
      labels:
       pod: nginx
     spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
